config/routes.rb
Rails.application.routes.draw do
  resources :tags do
    get :search, on: :collection
    resources :entries, only: :index do
      get :search, on: :collection
    end
  end
  resources :entries do
    get :search, on: :collection
  end
  resource :repository, only: [] do
    post :sync
  end
  resources :paths, only: :index
  resources :sessions, only: :new
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/(*path)(.*format)', to: 'welcome#index'
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_and_belongs_to_many :tags

  before_save :parse_title, :ensure_path

  def parse_title
    return if content.nil?

    title_string = content.scan(/^# .*/).first
    return title = 'untitled' if title_string.blank?

    self.title = title_string.slice(1..-1).strip
  end

  def ensure_path
    self.path = title if path.blank?
  end

  def self.search(query)
    return all if query.blank?

    where("path LIKE :query OR title LIKE :query OR content LIKE :query", query: "%#{query}%")
  end

  def self.create_by_file(file_path, relative_path: '.')
    file_name = Pathname.new(file_path).relative_path_from(Pathname.new(relative_path))
    entry = Entry.find_or_create_by(path: file_name.to_s)
    entry.update(content: File.read(file_path))
    Tag.parse(entry)
  end

  def self.with_directory
    where('path LIKE :query', query: '%/%')
  end

  def self.search_path(query)
    return all if query.blank?

    where("path LIKE :query", query: "#{query}%")
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = scope.order(updated_at: :desc)
  end

  def search
    render json: scope.search(params[:s])
  end

  # GET /entries/1
  # GET /entries/1.json
  def show; end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit; end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        Tag.parse(@entry)
        Tag.clean
        Wiki.save(@entry, current_user)
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      old_path = @entry.path
      if @entry.update(entry_params)
        Wiki.rename(@entry, old_path, current_user)
        Wiki.save(@entry, current_user)
        Tag.parse(@entry)
        Tag.clean
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    Tag.clean
    Wiki.delete(@entry, current_user)
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:path, :content)
    end

    def scope
      return @scope unless @scope.nil?
      return @scope = Entry.all unless params[:tag_id]

      @scope = Tag.find(params[:tag_id]).entries
    end
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.path %></td>
        <td><%= entry.title %></td>
        <td><%= entry.content %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @entry.path %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>